image: jelaniwoods/appdev2021-fortune-teller@sha256:754ba1af27f377de789bfeb2b021e9a1af19766dfe17dc0d9848bcac168253d7

tasks:
  - command: bundle install
  - init: bin/setup
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - shd101wyy.markdown-preview-enhanced
    - mbessey.vscode-rufo
    - aliariff.vscode-erb-beautify
